car/urls.py
from django.conf.urls import url
from . import views


app_name = 'car'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/$', views.details, name='details'),

]

cubito/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^car/',include('car.urls')),
]

car/models.py
from django.db import models


# Create your models here.
class car_id(models.Model):
    Trip = models.CharField(max_length=10)


class car_details(models.Model):
    Trip_name = models.ForeignKey(car_id, on_delete=models.CASCADE)
    Status = models.CharField(max_length=10, null=True)
    TimeDate = models.DateTimeField(null=True)
    Map = models.URLField(max_length=20, null=True)
    Lat = models.FloatField(null=True)
    Long = models.FloatField(null=True)

car/views.py
from urllib import response
from django.contrib.sites import requests
from django.http import HttpResponse
from django.shortcuts import render
import requests
import time
from car.models import car_id, car_details
from datetime import datetime


def index(response):
    car_id.objects.all().delete()
    for c in range(1, 10):
        request = requests.get('http://cubito.co.in/cab-location-assignment/')
        data = request.json()
        b = car_id()
        b.Trip = data['trip_id']
        b.save()
        all_car = car_id.objects.all()

    return render(response, 'car/index.html', {'all_car': all_car})


def details(request):
    tstart = datetime.now()
    tstop = datetime.now()
    state = "RUNNING"
    if request.method == "POST":
        print(request.POST)
        lr_name = request.POST['lol']
        while state == "RUNNING":
            b = car_id.objects.get(id=lr_name)
            name = b.Trip
            a = car_details()
            a.Trip_name = b
            real_data = requests.get("http://cubito.co.in/cab-location-assignment/?trip_id=" + b.Trip)
            data = real_data.json()
            a.Status = data['status']
            a.TimeDate = data['lastupdate']
            state = a.Status
            if tstart > tstop:
                tstart = datetime.now()
            tstop = datetime.now()
            a.Map = data['map']
            a.Lat = data['location']['latitude']
            a.Long = data['location']['longitude']
            a.save()
    all_car = car_id.objects.all()
    ok = car_details.objects.all()
    diff = tstop - tstart
    duration = divmod(diff.days * 86400 + diff.seconds, 60)
    context = {
        "map_points": ok,
        "all_car": all_car,
        "tstart": tstart,
        "tstop": tstop,
        "duration": duration,
        "name":name,
    }

    return render(request, 'car/details.html', context)

car/templates/car/details.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
    <head>
      <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="http://maps.google.com/maps/api/js?sensor=true">
        </script>

    </head>
    <style>

    #map {
        height: 400px;
        width: 700px;
        }

    </style>
    <body>
        <div class="container">
        <h1> Track Me</h1>
            <form action="{% url 'car:details'%}" method="post" class="form-horizontal">
                {% csrf_token %}
            <div class="form-group">
                <label class="control-label col-sm-2">Select an Trip:</label>
                <div class="col-sm-10">
                <select name="lol" class="form-control" id="opt">
                    {% for all in all_car %}
                      <option value="{{ all.id }}">{{ all.Trip }}</option><br>
                    {% endfor %}
                </select>
                </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2">
                <button type="submit" class="btn btn-info">Submit</button>
              </div>
                <div class="col-sm-pull-1 col-sm-2">
                        <button class="btn btn-danger"><a href="{% url 'car:index' %}" style="color: white">Get New Trip ID's</a> </button>
              </div>
            </div>
        </form>
        </div>
            <div id="map" class="container"></div><br>
        <div class="container">
          <h2>Trip Data</h2>
          <table class="table">
            <thead>
              <tr>
                <th>TRIP ID</th>
                <th>START TIME</th>
                <th>END TIME</th>
                  <th>DURATION(Minutes,Seconds)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{ name }}</td>
                <td>{{ tstart }}</td>
                <td>{{ tstop }}</td>
                  <td>{{ duration }}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <script>

    var locations = [
{% for point in map_points %}
    {% if point.Lat == None %}
    {% else %}
        ['{{ point.Trip }}', {{ point.Lat}}, {{ point.Long }}],
    {% endif %}
{% endfor%}
]


    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 4,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    navigator.geolocation && navigator.geolocation.getCurrentPosition(showPosition, showError) == undefined && showError();

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map

      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }

function showPosition(position) {
  lat = position.coords.latitude;
  lon = position.coords.longitude;
  latlon = new google.maps.LatLng(lat, lon);
  map.setCenter(latlon);
}

function showError(error) {
  map.setCenter(new google.maps.LatLng(locations[0][1], locations[0][2])); // default 1st from array
}

</script>
    </body>
</html>

car/templates/car/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1> Track Me</h1>

        <form action="{% url 'car:details'%}" method="post" class="form-horizontal">
                {% csrf_token %}
            <div class="form-group">
                <label class="control-label col-sm-2">Select an Trip:</label>
                <div class="col-sm-10">
                <select name="lol" class="form-control" id="opt">
                    {% for all in all_car %}
                      <option value="{{ all.id }}">{{ all.Trip }}</option><br>
                    {% endfor %}
                </select>
                </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2">
                <button type="submit" class="btn btn-info">Submit</button>
              </div>
                <div class="col-sm-pull-1 col-sm-2">
                        <button class="btn btn-danger"><a href="{% url 'car:index' %}" style="color: white">Get New Trip ID's</a> </button>
              </div>
            </div>
        </form>
    </div>


</body>
</html>